### ISSUE TITLE
React Native Navigation V2

### ISSUE THREAD

**Issue by saadqbal** [skrafft/react-native-jitsi-meet#21]
Hey @skrafft ,

I have successfully implemented your library on android with React-native-navigtaion. Bu i get the follwoing error on ios. Can you please help?

```
2019-02-14 00:25:54.608 [info][tid:com.facebook.react.RNJitsiMeetNavigatorManagerQueue][RNJitsiMeetNavigator.m:49] Initialize
2019-02-14 00:25:54.607719+0500 VideoApp[3176:725577] Initialize
2019-02-14 00:25:55.617 [info][tid:com.facebook.react.RNJitsiMeetNavigatorManagerQueue][RNJitsiMeetNavigator.m:56] Load URL https://meet.jit.si/test
2019-02-14 00:25:55.617744+0500 VideoApp[3176:726809] Load URL https://meet.jit.si/test
2019-02-14 00:25:55.618656+0500 VideoApp[3176:725382] -[RNNTabBarController pushViewController:animated:]: unrecognized selector sent to instance 0x109838000
2019-02-14 00:25:55.619398+0500 VideoApp[3176:725382] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RNNTabBarController pushViewController:animated:]: unrecognized selector sent to instance 0x109838000'
*** First throw call stack:
(0x1bc775ea4 0x1bb945a50 0x1bc68eb14 0x1e997e418 0x1bc77b7bc 0x1bc77d46c 0x104984e68 0x108704dc8 0x1087139a0 0x108704dc8 0x108712a78 0x1bc705ce4 0x1bc700bac 0x1bc7000e0 0x1be979584 0x1e9950c00 0x104130ed4 0x1bc1bebb4)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by skrafft** [comment]
Hi, can you post your AppDelegate.m file ?

**Comment by saadqbal** [comment]
Hi @skrafft Sure.

```

/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import <Firebase.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Fabric/Fabric.h>
#import <Crashlytics/Crashlytics.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTPushNotificationManager.h>
//#import "RCCManager.h"
#import <ReactNativeNavigation/ReactNativeNavigation.h>
#import "RNNotifications.h"


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  NSURL *jsCodeLocation;
#ifdef DEBUG
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
  
  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];

//  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
//  self.window.backgroundColor = [UIColor whiteColor];
//  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                     moduleName:@"RNMainApp"
                                              initialProperties:nil
                                                  launchOptions:launchOptions];
  
  NSString *newAgent = @"Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1";
  NSDictionary *dictionary = [[NSDictionary alloc] initWithObjectsAndKeys:newAgent, @"UserAgent", nil];
  [[NSUserDefaults standardUserDefaults] registerDefaults:dictionary];
  
  UIViewController *rootViewController = [UIViewController new];
  UINavigationController *navigationController = [[UINavigationController alloc]initWithRootViewController:rootViewController];
  navigationController.navigationBarHidden = YES;
  rootViewController.view = rootView;
  self.window.rootViewController = navigationController;
  
  [Fabric with:@[[Crashlytics class]]];
  return YES;
}

@end
```

**Comment by skrafft** [comment]
After checking your code and React Native Navigation, there's unfortunately not much I can do. RNN is replacing the navigationController needed for Jitsi with its own controller. I did not find any way to integrate the existing navigation controller into RNN tree structure. There's probably a way to do it by modifying RNN code to add an option to preserve the existing rootViewController inside a specific RNN Controller but I don't have time to do it.

**Comment by RicardoBer** [comment]
It's terrible, wix has make it's navigator very difficult to use, RNN is easy and we use a lot.

Any clues to test @skrafft or something that we can do?

**Comment by RicardoBer** [comment]
Hello again some advance on this?.

**Comment by skrafft** [comment]
@RicardoBer, unfortunately, I did not have time to check if we can do something with RNN to enable Jitsi. For now, I don't really have time to do it. Have you checked with them if there's a way to do it by modifying RNN code to add an option to preserve the existing rootViewController inside a specific RNN Controller.

**Comment by RicardoBer** [comment]
I having a lot of issues trying to make it works,
Xcode it's a nigthmare, It's more difficult make the compiler works tha develop code, you know.
I'll wait for someone posting here ideas or solutions.

Thanks anyway @skrafft .

@saadqbal puts similar issues on wix github for it's navigator, so the problem arrise with that navigator to, perhaps he return to this issue and put it's clues and discoveries.

**Comment by skrafft** [comment]
For now, I have no plan implementing it because I don't really have time. I'd be happy to accept a pull request though.

**Comment by jean-ben-guigui** [comment]
Not sure it would work but you could try to use react-native-navigation bridgeManagerDelegate option.

**Comment by skrafft** [comment]
Hi, I just published V2.0.0 which has been completely re-architectured and is compatible with RN 0.60.

The lib stops using native navigation controller to display the Jitsi View so it should now be compatible with React Native Navigation V2.

Please read the Readme file as the integration has changed: [README](https://github.com/skrafft/react-native-jitsi-meet/blob/master/README.md)

**Comment by cinder92** [comment]
@skrafft the issue has not been fixed, still having the same,
