### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by dhananjayharel** [skrafft/react-native-jitsi-meet#55]
My Android App crashes whenever I call 
   setTimeout(() => {
      JitsiMeet.call('https://meet.jit.si/roomName');
    }, 1000);

In my react app.

**Comment by Rana-Mohit** [comment]
Facing the same issue.
Log for the crash i am getting in android studio.
2019-08-30 19:02:37.678 29658-29658/com.jitsisdk E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jitsisdk, PID: 29658
    java.lang.AssertionError: Activity needs to be set if initial lifecycle state is resumed
        at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:35)
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:252)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:158)
        at org.jitsi.meet.sdk.BaseReactView.<init>(BaseReactView.java:104)
        at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:102)
        at com.reactnativejitsimeet.JitsiMeetNavigatorActivity.onCreate(JitsiMeetNavigatorActivity.java:62)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by dhananjayharel** [comment]
Same error.. seems that due to latest 
react-native >=0.60.0 version not sure .
https://community.jitsi.org/t/react-native-0-60/19363
my react-native version is 0.60.5

**Comment by Rana-Mohit** [comment]
@dhananjayharel 
Yes it is working with react-native version 0.59.8

**Comment by skrafft** [comment]
We need to wait for next version of jitsi sdk to fix this issue. For now, there's no workaround if you want to use RN > 0.60

**Comment by skrafft** [comment]
Hi, I just published V2.0.0 which has been completely re-architectured and is compatible with RN 0.60.

Please read the Readme file as the integration has changed: [README](https://github.com/skrafft/react-native-jitsi-meet/blob/master/README.md)

**Comment by LeoMosiah** [comment]
I'm having them same problem with my android build, i'm using react-native v0.61.1 and react-native-jitsi-meet v2.0.1, can someone help me?

**Comment by skrafft** [comment]
@LeoMosiah 
Are you sure that you have the same logcat error (Activity needs to be set if initial lifecycle state is resumed) with v2.0.1 ?

Normally, v2.0.1 uses v2.3.0 of Jitsi which has fixed this specific bug

**Comment by LeoMosiah** [comment]
I'm still trying to find why my app is crashes on android, I just downgraded my react-native to 0.60.6 and it stopped crashing, sry if I posted my problem on the wrong issue.

**Comment by LeoMosiah** [comment]
The error I'm receiving on my android emulator.
```2019-10-01 15:17:49.401 10116-10179/com.smash E/AndroidRuntime: FATAL EXCEPTION: ConnectivityThread
    Process: com.smash, PID: 10116
    java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/com.***-C89F9weOUEV2fGxYX75WHQ==/split_lib_dependencies_apk.apk)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:105)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.sendConnectivityChangedEvent(ConnectivityReceiver.java:74)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.updateConnectivity(ConnectivityReceiver.java:67)
        at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.updateAndSend(NetworkCallbackConnectivityReceiver.java:92)
        at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.access$300(NetworkCallbackConnectivityReceiver.java:27)
        at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver$ConnectivityNetworkCallback.onAvailable(NetworkCallbackConnectivityReceiver.java:100)
        at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:2770)
        at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:2969)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-10-01 15:17:49.414 10116-10179/com.smash E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/com.****-C89F9weOUEV2fGxYX75WHQ==/split_lib_dependencies_apk.apk)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:105)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.sendConnectivityChangedEvent(ConnectivityReceiver.java:74)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.updateConnectivity(ConnectivityReceiver.java:67)
        at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.updateAndSend(NetworkCallbackConnectivityReceiver.java:92)
        at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.access$300(NetworkCallbackConnectivityReceiver.java:27)
        at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver$ConnectivityNetworkCallback.onAvailable(NetworkCallbackConnectivityReceiver.java:100)
        at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:2770)
        at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:2969)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
    
    java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/com.****-C89F9weOUEV2fGxYX75WHQ==/split_lib_dependencies_apk.apk)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:105)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.sendConnectivityChangedEvent(ConnectivityReceiver.java:74)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.updateConnectivity(ConnectivityReceiver.java:67)
        at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.updateAndSend(NetworkCallbackConnectivityReceiver.java:92)
        at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.access$300(NetworkCallbackConnectivityReceiver.java:27)
        at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver$ConnectivityNetworkCallback.onAvailable(NetworkCallbackConnectivityReceiver.java:100)
        at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:2770)
        at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:2969)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-10-01 15:17:49.571 10116-10127/com.smash I/com.smash: Background concurrent copying GC freed 11028(1935KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 2MB/5MB, paused 418us total 165.645ms
2019-10-01 15:17:49.770 10116-10146/com.smash D/EGL_emulation: eglMakeCurrent: 0xebd6e900: ver 3 0 (tinfo 0xebe13960)
2019-10-01 15:17:49.913 10116-10116/com.smash D/ReactNative: ReactInstanceManager.detachViewFromInstance()
2019-10-01 15:17:51.566 10116-10172/com.smash I/ReactNativeJS: '[modules/browser/BrowserCapabilities.js]', 'This appears to be react-native, ver: 0.60.5'
2019-10-01 15:17:51.604 10116-10172/com.smash I/ReactNativeJS: '[modules/settings/Settings.js]', 'generated callstats uid', 'Rogelio-dzo'
2019-10-01 15:17:51.752 10116-10173/com.smash E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.RuntimeException: Could not invoke RNCNetInfo.getCurrentState
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:382)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26) 
        at android.os.Looper.loop(Looper.java:193) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/com.smash-C89F9weOUEV2fGxYX75WHQ==/split_lib_dependencies_apk.apk)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:105)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.getCurrentState(ConnectivityReceiver.java:42)
        at com.reactnativecommunity.netinfo.NetInfoModule.getCurrentState(NetInfoModule.java:50)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26) 
        at android.os.Looper.loop(Looper.java:193) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225) 
        at java.lang.Thread.run(Thread.java:764) 
    
    java.lang.RuntimeException: Could not invoke RNCNetInfo.getCurrentState
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:382)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26) 
        at android.os.Looper.loop(Looper.java:193) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/com.****-C89F9weOUEV2fGxYX75WHQ==/split_lib_dependencies_apk.apk)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:105)
        at com.reactnativecommunity.netinfo.ConnectivityReceiver.getCurrentState(ConnectivityReceiver.java:42)
        at com.reactnativecommunity.netinfo.NetInfoModule.getCurrentState(NetInfoModule.java:50)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26) 
        at android.os.Looper.loop(Looper.java:193) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225) 
        at java.lang.Thread.run(Thread.java:764) 
2019-10-01 15:17:51.752 10116-10173/com.smash I/Process: Sending signal. PID: 10116 SIG: 9
```

**Comment by skrafft** [comment]
The same problem has been encountered by Jitsi Meet SDK users on android in SDK < 2.4.0. Jitsi should release 2.4.0 soon and I'll publish a new version as soon as they publish theirs. In the meantime, if it works with 0.60.6, stick to this version.

**Comment by dpkpanchal38-web** [comment]
> @dhananjayharel
> Yes it is working with react-native version 0.59.8

i'm using same version but still app crashes.

**Comment by baotoan1905** [comment]
Tried with sdk 2.6.0 and 2.8.0 still same issue 
![image](https://user-images.githubusercontent.com/7258479/82523809-6e1bd800-9b57-11ea-874e-a860a8a35a24.png)

**Comment by vickyramz** [comment]
java.lang.SecurityException: PhoneAccount connection service requires BIND_TELECOM_CONNECTION_SERVICE permission.
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at com.android.internal.telecom.ITelecomService$Stub$Proxy.registerPhoneAccount(ITelecomService.java:1048)
	at android.telecom.TelecomManager.registerPhoneAccount(TelecomManager.java:1000)
	at org.jitsi.meet.sdk.ConnectionService.registerPhoneAccount(ConnectionService.java:328)
	at org.jitsi.meet.sdk.RNConnectionService.startCall(RNConnectionService.java:88)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
	at android.os.Looper.loop(Looper.java:201)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.telecom.PhoneAccountRegistrar.registerPhoneAccount(PhoneAccountRegistrar.java:678)
	at com.android.server.telecom.TelecomServiceImpl$1.registerPhoneAccount(TelecomServiceImpl.java:455)
	at com.android.internal.telecom.ITelecomService$Stub.onTransact(ITelecomService.java:237)
	at android.os.Binder.execTransact(Binder.java:726)










This issue is happening when jitsimeet.call in react native

**Comment by anantkrd** [comment]
App crashing on JitsiMeet.call(url,userInfo); 
any one found this crash solution for react native i am using version 0.62.2

**Comment by vickyramz** [comment]
Maybe you app crashing happening because of BIND Telecom permission in
android... You should change sdk version  under
nodemodule/react-native-jitsi/android/app/build.gradle
There you need to change jitsi sdk version

**Comment by harut7777** [comment]
> We need to wait for next version of jitsi sdk to fix this issue. For now, there's no workaround if you want to use RN > 0.60

Hi, is that error was fixed? i have the same problem, one time i could run it but after it it dont want to run

**Comment by daocaoren8318** [comment]
> The same problem has been encountered by Jitsi Meet SDK users on android in SDK < 2.4.0. Jitsi should release 2.4.0 soon and I'll publish a new version as soon as they publish theirs. In the meantime, if it works with 0.60.6, stick to this version.

my react-native version is 0.60.6 and Jitsi Meet SDK version is 2.4.0,but it still crashes

**Comment by liketodev4** [comment]
> > The same problem has been encountered by Jitsi Meet SDK users on android in SDK < 2.4.0. Jitsi should release 2.4.0 soon and I'll publish a new version as soon as they publish theirs. In the meantime, if it works with 0.60.6, stick to this version.
> 
> my react-native version is 0.60.6 and Jitsi Meet SDK version is 2.4.0,but it still crashes

File in android/app/src/main/assets/index.android.bundle named differently than specified in guide and name should be app.bundle.
Run this from project root to remove previous and generate correct app.bundle:
rm android/app/src/main/assets/index.android.bundle.

npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/app.bundle --assets-dest android/app/src/main/res/ && cd android && ./gradlew assembleDebug && cd .. && rm -rf android/app/src/main/res/drawable- && rm -rf android/app/src/main/res/raw/ && rm -rf android/app/src/main/assets/*

**Comment by harut7777** [comment]
> > The same problem has been encountered by Jitsi Meet SDK users on android in SDK < 2.4.0. Jitsi should release 2.4.0 soon and I'll publish a new version as soon as they publish theirs. In the meantime, if it works with 0.60.6, stick to this version.
> 
> my react-native version is 0.60.6 and Jitsi Meet SDK version is 2.4.0,but it still crashes

The file in android/app/src/main/assets/index.android.bundle named differently than specified in guide and name should be app.bundle.

Run this from project root to remove previous and generate correct app.bundle:

rm android/app/src/main/assets/index.android.bundle

npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/app.bundle --assets-dest android/app/src/main/res/ && cd android && ./gradlew assembleDebug && cd .. && rm -rf android/app/src/main/res/drawable- && rm -rf android/app/src/main/res/raw/ && rm -rf android/app/src/main/assets/*

**Comment by daocaoren8318** [comment]
> The error I'm receiving on my android emulator.
> 
> ```
>     Process: com.smash, PID: 10116
>     java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/com.***-C89F9weOUEV2fGxYX75WHQ==/split_lib_dependencies_apk.apk)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:105)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.sendConnectivityChangedEvent(ConnectivityReceiver.java:74)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.updateConnectivity(ConnectivityReceiver.java:67)
>         at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.updateAndSend(NetworkCallbackConnectivityReceiver.java:92)
>         at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.access$300(NetworkCallbackConnectivityReceiver.java:27)
>         at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver$ConnectivityNetworkCallback.onAvailable(NetworkCallbackConnectivityReceiver.java:100)
>         at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:2770)
>         at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:2969)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.os.HandlerThread.run(HandlerThread.java:65)
> 2019-10-01 15:17:49.414 10116-10179/com.smash E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
>     java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/com.****-C89F9weOUEV2fGxYX75WHQ==/split_lib_dependencies_apk.apk)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:105)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.sendConnectivityChangedEvent(ConnectivityReceiver.java:74)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.updateConnectivity(ConnectivityReceiver.java:67)
>         at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.updateAndSend(NetworkCallbackConnectivityReceiver.java:92)
>         at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.access$300(NetworkCallbackConnectivityReceiver.java:27)
>         at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver$ConnectivityNetworkCallback.onAvailable(NetworkCallbackConnectivityReceiver.java:100)
>         at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:2770)
>         at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:2969)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.os.HandlerThread.run(HandlerThread.java:65)
>     
>     java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/com.****-C89F9weOUEV2fGxYX75WHQ==/split_lib_dependencies_apk.apk)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:105)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.sendConnectivityChangedEvent(ConnectivityReceiver.java:74)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.updateConnectivity(ConnectivityReceiver.java:67)
>         at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.updateAndSend(NetworkCallbackConnectivityReceiver.java:92)
>         at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver.access$300(NetworkCallbackConnectivityReceiver.java:27)
>         at com.reactnativecommunity.netinfo.NetworkCallbackConnectivityReceiver$ConnectivityNetworkCallback.onAvailable(NetworkCallbackConnectivityReceiver.java:100)
>         at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:2770)
>         at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:2969)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.os.HandlerThread.run(HandlerThread.java:65)
> 2019-10-01 15:17:49.571 10116-10127/com.smash I/com.smash: Background concurrent copying GC freed 11028(1935KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 2MB/5MB, paused 418us total 165.645ms
> 2019-10-01 15:17:49.770 10116-10146/com.smash D/EGL_emulation: eglMakeCurrent: 0xebd6e900: ver 3 0 (tinfo 0xebe13960)
> 2019-10-01 15:17:49.913 10116-10116/com.smash D/ReactNative: ReactInstanceManager.detachViewFromInstance()
> 2019-10-01 15:17:51.566 10116-10172/com.smash I/ReactNativeJS: '[modules/browser/BrowserCapabilities.js]', 'This appears to be react-native, ver: 0.60.5'
> 2019-10-01 15:17:51.604 10116-10172/com.smash I/ReactNativeJS: '[modules/settings/Settings.js]', 'generated callstats uid', 'Rogelio-dzo'
> 2019-10-01 15:17:51.752 10116-10173/com.smash E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
>     java.lang.RuntimeException: Could not invoke RNCNetInfo.getCurrentState
>         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:382)
>         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
>         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
>         at android.os.Looper.loop(Looper.java:193)
>         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
>         at java.lang.Thread.run(Thread.java:764)
>      Caused by: java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
>         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150) 
>         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
>         at android.os.Handler.handleCallback(Handler.java:873) 
>         at android.os.Handler.dispatchMessage(Handler.java:99) 
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26) 
>         at android.os.Looper.loop(Looper.java:193) 
>         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225) 
>         at java.lang.Thread.run(Thread.java:764) 
>      Caused by: java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/com.smash-C89F9weOUEV2fGxYX75WHQ==/split_lib_dependencies_apk.apk)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:105)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.getCurrentState(ConnectivityReceiver.java:42)
>         at com.reactnativecommunity.netinfo.NetInfoModule.getCurrentState(NetInfoModule.java:50)
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371) 
>         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150) 
>         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
>         at android.os.Handler.handleCallback(Handler.java:873) 
>         at android.os.Handler.dispatchMessage(Handler.java:99) 
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26) 
>         at android.os.Looper.loop(Looper.java:193) 
>         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225) 
>         at java.lang.Thread.run(Thread.java:764) 
>     
>     java.lang.RuntimeException: Could not invoke RNCNetInfo.getCurrentState
>         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:382)
>         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
>         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
>         at android.os.Looper.loop(Looper.java:193)
>         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
>         at java.lang.Thread.run(Thread.java:764)
>      Caused by: java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
>         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150) 
>         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
>         at android.os.Handler.handleCallback(Handler.java:873) 
>         at android.os.Handler.dispatchMessage(Handler.java:99) 
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26) 
>         at android.os.Looper.loop(Looper.java:193) 
>         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225) 
>         at java.lang.Thread.run(Thread.java:764) 
>      Caused by: java.lang.NoSuchMethodError: No interface method putMap(Ljava/lang/String;Lcom/facebook/react/bridge/WritableMap;)V in class Lcom/facebook/react/bridge/WritableMap; or its super classes (declaration of 'com.facebook.react.bridge.WritableMap' appears in /data/app/com.****-C89F9weOUEV2fGxYX75WHQ==/split_lib_dependencies_apk.apk)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:105)
>         at com.reactnativecommunity.netinfo.ConnectivityReceiver.getCurrentState(ConnectivityReceiver.java:42)
>         at com.reactnativecommunity.netinfo.NetInfoModule.getCurrentState(NetInfoModule.java:50)
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371) 
>         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150) 
>         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
>         at android.os.Handler.handleCallback(Handler.java:873) 
>         at android.os.Handler.dispatchMessage(Handler.java:99) 
>         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26) 
>         at android.os.Looper.loop(Looper.java:193) 
>         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225) 
>         at java.lang.Thread.run(Thread.java:764) 
> 2019-10-01 15:17:51.752 10116-10173/com.smash I/Process: Sending signal. PID: 10116 SIG: 9
> ```

I have the same issue,how did you solve it?

**Comment by davidSmith96** [comment]
E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/oney/WebRTCModule/WebRTCModule$Options;
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:83)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.oney.WebRTCModule.WebRTCModule$Options" on path: DexPathList[[zip file "/data/app/com.justcodenow.bynfor-6lWpDIAmPt8LKssu9u0ErQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.justcodenow.bynfor-6lWpDIAmPt8LKssu9u0ErQ==/lib/x86, /data/app/com.justcodenow.bynfor-6lWpDIAmPt8LKssu9u0ErQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:83) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:919) 
    
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/oney/WebRTCModule/WebRTCModule$Options;
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:83)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.oney.WebRTCModule.WebRTCModule$Options" on path: DexPathList[[zip file "/data/app/com.justcodenow.bynfor-6lWpDIAmPt8LKssu9u0ErQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.justcodenow.bynfor-6lWpDIAmPt8LKssu9u0ErQ==/lib/x86, /data/app/com.justcodenow.bynfor-6lWpDIAmPt8LKssu9u0ErQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:83) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:919) 
E/InputDispatcher: channel '17cf240 com.justcodenow.bynfor/com.justcodenow.bynfor.dashBoard.DashboardActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/InputDispatcher: channel '3e754d6 com.justcodenow.bynfor/com.justcodenow.bynfor.dashBoard.liveAuction.jitsi.JitsiActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/tcodenow.bynfo: Unknown bits set in runtime_flags: 0x8000
E/AppIdleHistory: Error writing app idle file for user 0
E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
