### ISSUE TITLE
Jitsi-maven-repository update break android build.

### ISSUE THREAD

**Issue by jean-ben-guigui** [skrafft/react-native-jitsi-meet#57]
Hello,

React-native version: 0.59.10

I have added your sweet module to an app this summer. Everything was running smoothly until two days ago. Whithout any changes in the code, I suddenly wasn't able to compile my code on android, getting the following error:
`Error:
        Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.`

I made a new project and added one by one my different native modules to find out the one causing the error. I eventually figured out that it was react-native-jitsi-meet.
I followed the lead until I found out that the maven repo was updated 2 days ago with a breaking change: Jitsi meet SDK now uses a version of RN > 0.60.

So I forked jitsi's repository, rolled back a few commits before the breaking change and voilà.

For anyone having problem to compile on android, replace (in android/build.gradle)
`maven { 
url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases" 
}`
with
`maven { 
url "https://github.com/jean-ben-guigui/jitsi-maven-repository/raw/master/releases" 
}`

I have a question though. Since Jitsi is now in v0.60.5 are you planning to make a bump of the version any soon @skrafft ?

**Comment by skrafft** [comment]
Hi, I just published V2.0.0 which has been completely re-architectured and is compatible with RN 0.60.

Please read the Readme file as the integration has changed: [README](https://github.com/skrafft/react-native-jitsi-meet/blob/master/README.md)

**Comment by jean-ben-guigui** [comment]
Looking great. There is still a problem for people trying to use the plugin with a version of RN < 0.60.
The README should not advise to add `maven { url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases" }`, but another repo which contains the right version of the sdk. I don't mind the README pointing on my repo (I promise I won't touch this branch 😁) : 
`maven { url "https://github.com/jean-ben-guigui/jitsi-maven-repository/raw/release/v0.59/releases" }`.

**Comment by skrafft** [comment]
@jean-ben-guigui, maybe it did not understand your problem correctly but the way I see it, for RN < 0.60, you should use 1.2.0 of react-native-jitsi-meet which uses v2.1.0 of the sdk on android and a custom compiled version for ios. So the repo still remains the same.

**Comment by jean-ben-guigui** [comment]
Well, I am using:
RN 0.59.10
react-native-jitsi-meet 1.2.0

With this config if I use maven` { url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases" }` in my build.gradle, the android build fails.

I'll make a test starting from an empty project, but I am pretty sure that it won't work with that maven repo.

**Comment by jean-ben-guigui** [comment]
Okay, so I took the time to test.
I created a brand new project using 
`react-native init jitsiMeetRN --version react-native@0.59.10`
Then
`npm install react-native-jitsi-meet@1.2.0 --save`
And I followed the instructions from the Readme.

Finally, when I run react-native run-android I get the following error:
![image](https://user-images.githubusercontent.com/15104156/66128085-653cbd00-e5ed-11e9-88bf-3be2780a5cb6.png)

Though, when I replace the line
`maven { url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases" }`
with
`maven { url "https://github.com/jean-ben-guigui/jitsi-maven-repository/raw/master/releases" }`
everything runs smoothly.

**Comment by batuhansahan** [comment]
@jean-ben-guigui how did you publish maven repository like [release/v0.59/releases](https://github.com/jean-ben-guigui/jitsi-maven-repository/raw/release/v0.59/release)

Can you explain ? please.

**Comment by jean-ben-guigui** [comment]
I explained it there:
https://github.com/skrafft/react-native-jitsi-meet/issues/93#issuecomment-572993800

If you have any questions feel free to ask.

**Comment by batuhansahan** [comment]
well i have folder with com and org file but when i push git it's not like you and i cannot use it, 

also i didnt do any maven deploy kind thing and didn't touch pom file or generate it.

**Comment by jean-ben-guigui** [comment]
Okay, I am not sure I understand what you are trying to do.
What is the original problem?

If you have a wrong sdk version, what you have to do is fork [this repo](https://github.com/jitsi/jitsi-maven-repository) then explore the commits. When you find a commit where the sdk version is the same as yours, you checkout that commit and you are good.
